### ISSUE TITLE
https proxy

### ISSUE THREAD

**Issue by idoshamun** [just-containers/nginx-loadbalancer#12]
I think there is a need for https proxy not just http.
I came across some servers which don't handle well http -> https reverse proxy.

**Comment by glerchundi** [comment]
nginx 1.8.x introduced "Backend SSL certificate verification", since I implemented the `.nginx` functionality I think this can be worked around, WDYT?

[`proxy_ssl_verify`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_verify)

**Comment by idoshamun** [comment]
Not sure if I understood correctly this module

**Comment by glerchundi** [comment]
Something like this:

```
/lb
  /hosts
    /lisa.contoso.com
      /listeners
        /ls1 = '{
          "protocol": "http",
          "address": "0.0.0.0:80"
        }'
      /locations
        /loc1
          /.nginx = '{
            "proxy_ssl_verify": on
          }'
          /value = '{
            "path": "/api",
            "upstream": "up1"
          }'
  /upstreams
    /up1
      /servers
        /e1 = '{ "url": "https://10.10.10.10" }'
```

**Comment by idoshamun** [comment]
Looks great!

**Comment by glerchundi** [comment]
@idosh i'm going to close this issue because i tested it and it works on my test env.
