### ISSUE TITLE
Question about initialize-log-fds script

### ISSUE THREAD

**Issue by robinroestenburg** [just-containers/nginx-loadbalancer#6]
Hi,

I have a question about the `initialize-log-fds` script. You create the log directories like this:

```
if { s6-mkdir -p /var/log/nginx-access }  
if { s6-envuidgid deployer s6-chown -U /var/log/nginx-access }
if { s6-chmod 2700 /var/log/nginx-access }
```

Can those last two lines also be performed using `fix-attrs.d` script or do the permission need to be correct before registering the fifo in the fdholderd?

Thanks for your work on this, much appreciated :+1:

**Comment by glerchundi** [comment]
Hei,

Yes it can be done in that way but I wanted to avoid creating folders inside the `Dockerfile` and there is no elegant way of creating empty directories in git without adding dummy files to it, so I refused. I'm going to create them using `.gitkeep` although I don't feel very confortable with that!

thanks for reminding me!

**Comment by glerchundi** [comment]
Umm, after looking at the source (i forgot why i did that ...), it was done it that way primarily because `fix-attrs.d` doesn't implement fallbacking to default uid/gid's like `s6-envuidgid` does:

```
if { s6-mkdir -p /var/log/nginx-error-logs }
if { s6-envuidgid -D 32768:32768 nobody s6-chown -U /var/log/nginx-error-logs }
if { s6-chmod 2700 /var/log/nginx-error-logs }
```

That's why :-)

**Comment by robinroestenburg** [comment]
Ah, right. Thanks :)
